#!/usr/bin/env python3
"""models.raw.json + cards.json  ->  src/models.gen.ts  (HTML pre-rendered at build time)."""
import json, re, html, markdown

raw   = json.load(open("data/models.raw.json"))
cards = json.load(open("data/cards.json"))
icons = json.load(open("data/icons.json"))   # gemini-drawn

MD = markdown.Markdown(extensions=["tables", "fenced_code", "sane_lists", "attr_list"])

def render(md_text: str, slug: str) -> str:
    # Strip the H1 (the page renders its own title) and the leading blank lines.
    body = re.sub(r'^#\s+.+\n', '', md_text, count=1).lstrip()
    MD.reset()
    out = MD.convert(body)
    # Cross-links: `thinking-foo` -> anchor, but never self-link.
    def link(m):
        s = m.group(1)
        if s == slug or s not in by_slug: return m.group(0)
        return (f'<a class="xref" href="/tools/models/m/{s.removeprefix("thinking-")}">'
                f'{html.escape(by_slug[s]["title"])}</a>')
    out = re.sub(r'<code>(thinking-[a-z0-9-]+)</code>', link, out)
    # Checklist boxes
    out = out.replace("<li>[ ] ", '<li class="chk">').replace("<li>[x] ", '<li class="chk done">')
    return section_boxes(out)


# Sections that earn their own visual treatment on the page. Everything else
# renders as plain prose, so these three actually stand out.
BOXED = {
    "Trigger Card": "box trigger",
    "When NOT to Use": "box caution",
    "Verification Checklist": "box check",
}


def section_boxes(html_out: str) -> str:
    """Wrap named H2 sections in a styled box, from the heading to the next H2."""
    parts = re.split(r'(<h2[^>]*>.*?</h2>)', html_out, flags=re.S)
    out, i = [], 0
    while i < len(parts):
        chunk = parts[i]
        m = re.match(r'<h2[^>]*>(.*?)</h2>', chunk, re.S)
        label = re.sub(r'<[^>]+>', '', m.group(1)).strip() if m else None
        if label in BOXED:
            body = parts[i + 1] if i + 1 < len(parts) else ""
            out.append(f'<section class="{BOXED[label]}">{chunk}{body}</section>')
            i += 2
        else:
            out.append(chunk)
            i += 1
    return "".join(out)

# The sections Claude needs to actually RUN the model against a real situation.
# Overview/When-to-use/Sources are for a human browsing; they only pad the prompt.
METHOD_SECTIONS = (
    "Trigger Card", "The Process", "The Four Components", "The Four Quadrants",
    "The Three Outcomes", "The Four Openings", "Application Patterns",
    "Worked Example", "Common Failure Modes", "Verification Checklist", "Key Questions",
)


def method_sections(md_text: str) -> str:
    keep, cur = [], False
    for line in md_text.splitlines():
        h = re.match(r'##\s+(.+)', line)
        if h:
            cur = h.group(1).strip() in METHOD_SECTIONS
        if cur:
            keep.append(line)
    return "\n".join(keep).strip()


by_slug = {m["slug"]: m for m in raw}
models = []
for m in raw:
    c = cards[m["slug"]]
    trig = re.search(r'##\s+Trigger Card\n(.*?)(?=\n##\s|\Z)', m["markdown"], re.S)
    method = method_sections(m["markdown"])
    models.append({
        "slug": m["slug"],
        "id": m["slug"].removeprefix("thinking-"),
        "title": m["title"],
        "category": c["category"],
        "blurb": c["blurb"],
        "question": c["question"],
        "description": m["description"],
        "trigger": " ".join(trig.group(1).split())[:600] if trig else "",
        "method": method,
        "icon": icons[m["slug"].removeprefix("thinking-")],
        "html": render(m["markdown"], m["slug"]),
    })

CATS = ["Problem solving","Decision making","Systems thinking","Communication",
        "Risk","Innovation","Evaluation","Estimation","Self-awareness"]
cats = [c for c in CATS if any(m["category"] == c for m in models)]

ts = (
    "// GENERATED by scripts/build-data.py — do not edit by hand.\n"
    "// Source: ~/.claude/thinking-models/*.md + ox cards (data/cards.json) + gemini icons (data/icons.json)\n\n"
    "export type Model = {\n"
    "  slug: string; id: string; title: string; category: string;\n"
    "  blurb: string; question: string; description: string; trigger: string;\n"
    "  /** The operative sections only — what Claude needs to run the model. */\n"
    "  method: string;\n"
    "  icon: string; html: string;\n"
    "};\n\n"
    f"export const CATEGORIES: string[] = {json.dumps(cats)};\n\n"
    f"export const MODELS: Model[] = {json.dumps(models, ensure_ascii=False)};\n\n"
    "export const BY_ID = new Map(MODELS.map((m) => [m.id, m]));\n"
)
open("src/models.gen.ts", "w").write(ts)
print(f"{len(models)} models, {len(cats)} categories, {len(ts)//1024}KB")
